kind: pipeline
name: default

steps: 
  - name: build
    image: docker
    commands:
    - docker build --build-arg RKE_VERSION=v0.2.1 -t lukasbahr/rke-docker:v0.2.1 .
    volumes:
    - name: socket
      path: /var/run/docker.sock
  - name: publish
    image: plugins/docker
    when:
      branch: 
      - master
    settings:
      repo: lukasbahr/rke-docker
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      tags = [
       - latest
       - ${DRONE_TAG}
      auto_tag: true
      force_tag: true
# make sure repo is trusted in drone.ci
volumes:
  - name: socket
    host:
      path: /var/run/docker.sock
