kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps: 
  - name: build-and-push-dockerimage
    image: plugins/docker
    when:
      branch: 
      - master
    build_args:
     - RKE_VERSION=v0.2.2
     - ARCHITECTURE=amd64
    settings:
      repo: lukasbahr/rke-docker
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      tags:
       - latest
       - 'amd64-v0.2.1'

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps: 
  - name: build-and-push-dockerimage
    image: plugins/docker
    when:
      branch: 
      - master
    build_args:
      - RKE_VERSION=v0.2.2
      - ARCHITECTURE=arm64
    settings:
      repo: lukasbahr/rke-docker
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      tags:
       - 'arm64-v0.2.1'